import { useEffect, useState, type FormEvent } from 'react'
import { LoginGate, Field } from '../components/CommerceShell'
import { commerceRequest, money, bookingTime } from '../lib/commerce'
type Store = { id:string; name:string; region:string; orders:number; statuses:Record<string,number>; repeat_buyers:number; quote_confirmed_orders:number; founder_minutes:number; team_minutes:number; new_platform_orders:number; existing_customer_orders:number }
type Summary = { scope:string; merchants:Store[]; cross_merchant_buyers:number; simulated_paid_fen:number; simulated_fee_fen:number }
type Log = { id:string; actor:string; minutes:number; attribution:string; note:string; created_at:string }
type Billing = { paid_fen:number; fee_fen:number; net_fen:number; refunded_fen:number }
type Fee = { basis_points:number; flat_fen:number; can_edit:boolean }
export function CommerceOperationsPage() { return <LoginGate><Operations /></LoginGate> }
function Operations() {
  const [summary,setSummary] = useState<Summary|null>(null); const [selected,setSelected]=useState(''); const [logs,setLogs]=useState<Log[]>([]); const [billing,setBilling]=useState<Billing|null>(null); const [fee,setFee]=useState<Fee|null>(null)
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function overview() { const data=await commerceRequest<Summary>('/api/commerce/operations'); setSummary(data); setSelected(old=>data.merchants.some(m=>m.id===old)?old:data.merchants[0]?.id || '') }
  async function details(id:string) { const [l,b,f]=await Promise.all([commerceRequest<Log[]>(`/api/merchants/${id}/pilot-logs`),commerceRequest<Billing>(`/api/merchants/${id}/billing`),commerceRequest<Fee>(`/api/merchants/${id}/fee-policy`)]); setLogs(l);setBilling(b);setFee(f) }
  useEffect(()=>{overview().catch((e:Error)=>setError(e.message))},[])
  useEffect(()=>{let alive=true;setLogs([]);setBilling(null);setFee(null);if(selected) { Promise.all([commerceRequest<Log[]>(`/api/merchants/${selected}/pilot-logs`),commerceRequest<Billing>(`/api/merchants/${selected}/billing`),commerceRequest<Fee>(`/api/merchants/${selected}/fee-policy`)]).then(([l,b,f])=>{if(alive){setLogs(l);setBilling(b);setFee(f)}}).catch((e:Error)=>{if(alive)setError(e.message)}) };return()=>{alive=false}},[selected])
  async function record(e:FormEvent<HTMLFormElement>) {e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try {await commerceRequest(`/api/merchants/${selected}/pilot-logs`,{method:'POST',body:JSON.stringify({actor:d.get('actor'),category:d.get('category'),minutes:Number(d.get('minutes')),attribution:d.get('attribution'),note:d.get('note'),order_id:d.get('order') || null})});await overview();await details(selected)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function saveFee(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await commerceRequest(`/api/merchants/${selected}/fee-policy`,{method:'PUT',body:JSON.stringify({basis_points:Number(d.get('bps')),flat_fen:Number(d.get('flat'))})});await details(selected)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><p className="eyebrow">OPERATIONS / 试点验证</p><h1>看见订单，也看见人工成本。</h1><p className="lead">记录商家入驻、客户来源、复购与人工介入，验证服务闭环能否独立运转。</p>{error&&<p role="alert" className="commerce-error">{error}</p>}
    {summary&&<><p className="muted">当前范围：{summary.scope==='platform'?'平台运营':'我管理的商家'}。跨商家完成服务的用户：{summary.cross_merchant_buyers}。来源未知的订单不计为平台新增。</p><div className="metrics-grid">{summary.merchants.map(m=><article className="commerce-card" key={m.id}><h2>{m.name}</h2><p>{m.region} · {m.orders} 单 · 完成 {m.statuses.completed||0} 单</p><p>复购用户 {m.repeat_buyers} · 报价确认订单 {m.quote_confirmed_orders}</p><p>平台新增 {m.new_platform_orders} · 老客 {m.existing_customer_orders}</p><p>创始人 {m.founder_minutes} 分钟 · 团队 {m.team_minutes} 分钟</p><button className="secondary" onClick={()=>setSelected(m.id)}>查看与记录</button></article>)}</div>
    {summary.merchants.length===0?<p className="commerce-card">先在商家工作台开通店铺。</p>:<><Field label="当前店铺"><select value={selected} onChange={e=>setSelected(e.target.value)}>{summary.merchants.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></Field>
    <div className="workspace-grid"><form className="commerce-card editor" onSubmit={record}><h2>记录试点工作</h2><Field label="操作人"><select name="actor"><option value="founder">创始人</option><option value="team">团队</option></select></Field><Field label="工作类型"><select name="category"><option value="onboarding">商家入驻</option><option value="operation">接单与履约</option><option value="support">售后</option></select></Field><Field label="用时（分钟）"><input type="number" name="minutes" min={0} max={1440} required/></Field><Field label="关联订单编号（可留空）"><input name="order" /></Field><Field label="客户来源"><select name="attribution"><option value="unknown">未知</option><option value="existing_customer">商家已有客户</option><option value="new_platform">平台带来的新客户</option></select></Field><Field label="实际工作说明"><textarea name="note" required maxLength={1500}/></Field><button className="primary" disabled={busy}>保存记录</button></form>
    <section><div className="commerce-card"><h2>本地模拟账单</h2><p className="muted">这些金额用于验证收费规则，不代表收入或真实结算。</p>{billing&&<><p>已模拟支付 {money(billing.paid_fen)}</p><p>模拟平台费 {money(billing.fee_fen)} · 商家净额 {money(billing.net_fen)}</p><p>已模拟退款 {money(billing.refunded_fen)}</p></>}{fee&&<><p>费率 {fee.basis_points/100}% + 每单 {money(fee.flat_fen)}</p>{fee.can_edit&&<form key={selected} onSubmit={saveFee}><Field label="费率（基点：100 = 1%）"><input name="bps" type="number" min={0} max={10000} defaultValue={fee.basis_points} required/></Field><Field label="每单固定费用（分）"><input name="flat" type="number" min={0} max={1000000} defaultValue={fee.flat_fen} required/></Field><button className="secondary" disabled={busy}>保存模拟费率</button></form>}</>}</div>
    <h2>最近工作记录</h2>{logs.map(l=><article className="commerce-card" key={l.id}><p>{bookingTime(l.created_at)} · {l.actor==='founder'?'创始人':'团队'} · {l.minutes} 分钟</p><p>{l.note}</p><p className="muted">来源：{l.attribution==='new_platform'?'平台新增':l.attribution==='existing_customer'?'商家老客':'未知'}</p></article>)}</section></div>
    </>}</>}
  </>
}
