import { useState, type FormEvent } from 'react'
import { Field } from './CommerceShell'
import { commerceRequest, money, type Booking } from '../lib/commerce'
type Payment = { id: string; provider: string; amount_fen: number; fee_fen: number; status: string }
type Refund = { id: string; status: string; reason: string; resolution: string }
type Case = { id: string; subject: string; description: string; status: string; resolution: string }
const labels: Record<string,string> = { paid: '已模拟支付', refunded: '已模拟退款', requested: '待处理', processed: '已退款', declined: '已拒绝', open: '待处理', resolved: '商家已回复', closed: '已关闭' }
export function OrderAftercare({ order, merchantId }: { order: Booking; merchantId?: string }) {
  const [open, setOpen] = useState(false); const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const [mode, setMode] = useState('disabled'); const [finance, setFinance] = useState<{ payment: Payment | null; refund: Refund | null }>({ payment: null, refund: null }); const [cases, setCases] = useState<Case[]>([])
  const [requestId] = useState(() => { const b = crypto.getRandomValues(new Uint8Array(16)); b[6] = (b[6]&15)|64; b[8]=(b[8]&63)|128; const s = Array.from(b,x=>x.toString(16).padStart(2,'0')).join(''); return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}` })
  async function refresh() { const [f,c,p] = await Promise.all([commerceRequest<typeof finance>(`/api/orders/${order.id}/finance`), commerceRequest<Case[]>(`/api/orders/${order.id}/cases`), commerceRequest<{ mode: string }>('/api/commerce/payments/capabilities',{},false)]); setFinance(f); setCases(c); setMode(p.mode); setLoaded(true) }
  async function mutate(path: string, body?: unknown) { setBusy(true); setError(''); setNotice(''); try { await commerceRequest(path,{method:'POST',...(body ? {body:JSON.stringify(body)} : {})}); await refresh(); setNotice('操作已保存。系统投递可在工作台的投递记录中查看。') } catch(e) {setError((e as Error).message)} finally {setBusy(false)} }
  async function reveal() { const next = !open; setOpen(next); if(next) { setBusy(true); setError(''); try { await refresh() } catch(e) {setError((e as Error).message)} finally {setBusy(false)} } }
  function form(event: FormEvent<HTMLFormElement>, kind: 'refund' | 'case' | 'resolve', id?: string) { event.preventDefault(); const d = new FormData(event.currentTarget); if(kind==='refund') void mutate(`/api/orders/${order.id}/refunds`,{reason:d.get('reason')}); else if(kind==='case') void mutate(`/api/orders/${order.id}/cases`,{subject:d.get('subject'),description:d.get('description')}); else void mutate(`/api/merchants/${merchantId}/cases/${id}/resolve`,{resolution:d.get('resolution')}) }
  return <div className="aftercare"><button className="secondary" type="button" onClick={reveal}>{open ? '收起账单与售后' : '查看账单与售后'}</button>{open && <>
    {notice && <p role="status" className="commerce-notice">{notice}</p>}{error && <p role="alert" className="commerce-error">{error}</p>}{busy && <p role="status">正在处理…</p>}
    {loaded && <><p className="muted">{mode === 'local_simulated' ? '支付演练模式：不扣款、不转账，所有金额均为模拟账目。' : '在线支付尚未启用。'}</p>
    {finance.payment && <p>{labels[finance.payment.status]} · {money(finance.payment.amount_fen)} · 模拟平台费 {money(finance.payment.fee_fen)}</p>}
    {!merchantId && mode==='local_simulated' && !finance.payment && order.status==='accepted' && <form onSubmit={e=>{e.preventDefault();void mutate(`/api/orders/${order.id}/payments`,{request_id:requestId,confirmed:true})}}><label className="checkbox-field"><input type="checkbox" required />我确认演练支付 {money(order.price_fen)}，不会产生真实扣款。</label><button className="primary" disabled={busy}>确认模拟支付</button></form>}
    {finance.refund && <div><h3>退款：{labels[finance.refund.status]}</h3><p>{finance.refund.reason}</p><p>{finance.refund.resolution}</p>{merchantId && finance.refund.status==='requested' && <form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);void mutate(`/api/merchants/${merchantId}/refunds/${finance.refund!.id}/resolve`,{approve:d.get('decision')==='approve',resolution:d.get('resolution')})}}><Field label="处理结果"><select name="decision"><option value="approve">同意模拟退款</option><option value="decline">拒绝退款</option></select></Field><Field label="说明"><textarea name="resolution" required maxLength={2000}/></Field><button className="primary" disabled={busy}>提交处理结果</button></form>}</div>}
    {!merchantId && finance.payment?.status==='paid' && !finance.refund && <form onSubmit={e=>form(e,'refund')}><Field label="退款原因"><textarea name="reason" required maxLength={2000}/></Field><button className="secondary" disabled={busy}>申请模拟退款</button></form>}
    {merchantId && (order.status === 'accepted' || order.status === 'completed') && <button className="secondary" disabled={busy} onClick={() => mutate(`/api/merchants/${merchantId}/integrations/orders/${order.id}`, { system: 'local-example' })}>加入本地示例投递队列</button>}
    <h3>售后记录</h3>{cases.length===0 && <p className="muted">暂无售后记录。</p>}{cases.map(c=><div className="case-record" key={c.id}><strong>{c.subject} · {labels[c.status]}</strong><p>{c.description}</p><p>{c.resolution}</p>{merchantId && c.status!=='closed' && <form onSubmit={e=>form(e,'resolve',c.id)}><Field label="商家回复"><textarea name="resolution" required maxLength={3000}/></Field><button className="secondary" disabled={busy}>提交回复</button></form>}{!merchantId && c.status==='resolved' && <button className="secondary" disabled={busy} onClick={()=>mutate(`/api/commerce/cases/${c.id}/close`)}>确认解决并关闭</button>}</div>)}
    {!merchantId && <form onSubmit={e=>form(e,'case')}><Field label="售后主题"><input name="subject" required maxLength={100}/></Field><Field label="问题说明"><textarea name="description" required maxLength={3000}/></Field><button className="secondary" disabled={busy}>提交售后问题</button></form>}
    </>}
  </>}</div>
}
